version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_api
    restart: always
    ports:
      - "8080:8080"
    links:
      - db1
    depends_on:
      - db1

  my_database:
    build:
      context: ./mysql
      dockerfile: Dockerfile_data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: sample
      MYSQL_USER: user01
      MYSQL_PASSWORD: password