version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile_api1
    restart: always
    ports:
      - "8080:8080"
    links:
      - db:my_database
    #depends_on:
     # - db:my_database

  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile_data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: sample
      MYSQL_USER: user01
      MYSQL_PASSWORD: password